// User
GET http://localhost:3000/User

###

GET http://localhost:3000/User/66558a6732c43e48f5a24888

###

POST http://localhost:3000/User
Content-Type: application/json

{
    "userName" : "Quan",
    "userPassword" : "1231231"
}

###

PATCH http://localhost:3000/User/66558a6732c43e48f5a24888
Content-Type: application/json

{
    "userPassword" : "Thong"
}

###

DELETE http://localhost:3000/User/66558956ebd1b0ba35d42d2f


###

//Room

GET http://localhost:3000/Room

###

GET http://localhost:3000/Room/66559be06275888693d25730

###

POST http://localhost:3000/Room
Content-Type: application/json

{
    "roomId" : 2,
    "roomPassword" : "q3qeqeq"
}

###

PATCH http://localhost:3000/Room/66559be06275888693d25730
Content-Type: application/json

{
    "roomPassword" : "1231231asda"
}

###

DELETE http://localhost:3000/User/66558956ebd1b0ba35d42d2f
